services:
  - type: web
    name: veridium
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: WEBAUTHN_RP_NAME
        value: Veridium
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: false 